export {
  DogDetailsContainer,
  DogImageContainer,
  DogImage,
  LowerDataContainer,
  DogsName,
  DogsBreed,
  BackIcon,
  HeartIcon,
  GenderText,
  BoxesContainer,
  DataBox,
  DataBoxTextBold,
  DataBoxText,
  StoryContainer,
  StoryTitle,
  StoryDetails,
  OtherDetailsBoxContainer,
  OtherDetailsContainer,
  OtherDetailsTitle,
  OtherDetailsText,
  ShelterContactButton,
  ShelterContactButtonText,
} from './DogDetails';
